import React from "react";
import { View, Text, ActivityIndicator } from "react-native";
import tw from "tailwind-react-native-classnames";

export const UserMessage = ({ message }: { message: string }) => (
  <View
    style={[
      tw`rounded-2xl rounded-br-none py-3 px-4 self-end mb-2`,
      {
        backgroundColor: "#14b8a6",
        maxWidth: "75%",
      },
    ]}
  >
    <Text style={tw`text-white`}>{message}</Text>
  </View>
);

export const BotMessage = ({ message }: { message: string }) => (
  <View
    style={[
      tw`bg-gray-200 rounded-2xl rounded-bl-none py-3 px-4 self-start mb-2`,
      { maxWidth: "75%" },
    ]}
  >
    <Text style={tw`text-gray-800`}>{message}</Text>
  </View>
);

export const DisclaimerMessage = () => (
  <View
    style={tw`bg-yellow-100 border border-yellow-300 rounded-lg py-2 px-3 self-start mb-4`}
  >
    <Text style={tw`text-yellow-800 text-xs font-medium`}>
      DISCLAIMER: This feedback is generated by AI and is not a substitute for
      professional medical advice. Always consult with your healthcare provider
      before starting, changing, or stopping any exercise program.
    </Text>
  </View>
);

export const LoadingMessage = () => (
  <View
    style={tw`self-start bg-gray-200 rounded-2xl rounded-bl-none py-3 px-4 mb-2`}
  >
    <ActivityIndicator size="small" color="#14b8a6" />
  </View>
);
