# Generated by Django 5.1.1 on 2025-02-26 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercisecategory',
            name='video_link',
        ),
        migrations.AddField(
            model_name='exercise',
            name='video_link',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
