# Generated by Django 5.1.1 on 2025-02-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
