# Generated by Django 5.1.1 on 2025-02-18 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_exercise_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('user', 'date')},
        ),
    ]
