# Generated by Django 5.1.1 on 2025-03-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_report_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportexercise',
            name='pain_level',
            field=models.IntegerField(default=0),
        ),
    ]
