# Generated by Django 5.1.1 on 2025-02-19 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_report_summary_alter_report_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='exercise',
            new_name='category',
        ),
    ]
