# Generated by Django 5.1.1 on 2025-03-05 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_reportexercise_pain_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexercise',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
