# Generated by Django 5.1.1 on 2025-02-25 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_exercise_exercise_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='InjuryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='', max_length=500)),
                ('treatment', models.ManyToManyField(blank=True, to='api.exercise')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='injury_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.injurytype'),
        ),
    ]
