# Generated by Django 5.1.1 on 2025-02-25 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_injurytype_user_injury_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='exercisecategory',
            options={'ordering': ['name'], 'verbose_name': 'Exercise Category', 'verbose_name_plural': 'Exercise Categories'},
        ),
        migrations.AddField(
            model_name='exercise',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='exercisecategory',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='api.exercisecategory'),
        ),
    ]
