# Generated by Django 5.1.1 on 2025-03-10 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_userexercise_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_reset',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
