# Generated by Django 5.1.1 on 2025-02-25 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_exercise_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexercise',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userexercise',
            name='pain_level',
            field=models.IntegerField(default=0),
        ),
    ]
