# Generated by Django 5.1.1 on 2025-04-20 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_user_pain_level_userexercise_hold'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='video_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
