# Generated by Django 5.1.1 on 2025-04-24 10:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_exercise_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexercise',
            name='date_activated',
            field=models.DateField(auto_now_add=True, default=datetime.date(2025, 4, 19)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userexercise',
            name='date_deactivated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
