# Generated by Django 5.1.1 on 2025-04-25 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_userexercise_date_activated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='summary',
        ),
    ]
