# Generated by Django 5.1.1 on 2025-04-25 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_reportexercise_exercise_removed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportexercise',
            name='exercise_removed',
        ),
    ]
