# Generated by Django 5.1.1 on 2025-04-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_reportexercise_exercise_removed'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='end',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='exercise',
            name='start',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
