# Generated by Django 5.1.1 on 2025-04-29 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_exercise_end_exercise_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='hold',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
