# Generated by Django 5.1.1 on 2025-04-29 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_exercise_hold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='hold',
            field=models.IntegerField(default=0),
        ),
    ]
